vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: /avatar
            upload_destination: '%kernel.project_dir%/public/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        game_image:
            uri_prefix: /game_image
            upload_destination: '%kernel.project_dir%/public/game_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
